CSL 2338 - Export catalog parameters as types
Constructor-io/constructorio-node pull request #154
Opened 2023-05-17 17:16 UTC by mocca102

2023-05-18 00:30 UTC, stanlp1 requested changes
Minor comment about casing. Rest looks good to me.

2023-05-18 00:30 UTC, stanlp1 commented on src/types/catalog.d.ts
> +  parent_id?: string;
I think for node, with the pr from 1 month ago, we changed all the parameters to camel case. Should we change the types as well?

2023-05-18 00:33 UTC, stanlp1 commented
<img width="657" alt="Screenshot 2023-05-17 at 5 32 47 PM" src="https://github.com/Constructor-io/constructorio-node/assets/57369888/50ccdb1a-4e98-4d73-acc5-45da1fbb78fe">


Also, should we use these exported types in the function types themselves? That way we can keep it in one place.

2023-05-18 17:06 UTC, stanlp1 commented on src/types/catalog.d.ts
> +export interface UpdateItemParameters extends CreateOrReplaceItemsParameters {}
I think we are missing on_missing here too.

2023-05-19 12:20 UTC, mocca102 commented
@stanlp1 Created stories for the casing and missing parameters to be addressed in a separate PR
https://linear.app/constructor/issue/CSL-2414/node-sdk-add-on-missing-parameter-type-to-catalog-module
https://linear.app/constructor/issue/CSL-2412/node-sdk-update-parameters-casing-to-be-camelcase

2023-05-23 20:07 UTC, merged