[CSL-802] Add quizzes to node
Constructor-io/constructorio-node pull request #84
Opened 2022-01-25 22:24 UTC by stanlp1

2022-01-25 22:46 UTC, stanlp1 commented on src/modules/quizzes.js
> +   * @param {object} [userParameters] - Parameters relevant to the user request
Search and browse had userParameters like below so I added some of them here. I'm not sure if these endpoints will be tracked on a user basis, or if I should remove these parameters.

`   * @param {object} [userParameters] - Parameters relevant to the user request
   * @param {number} [userParameters.sessionId] - Session ID, utilized to personalize results
   * @param {number} [userParameters.clientId] - Client ID, utilized to personalize results
   * @param {string} [userParameters.userId] - User ID, utilized to personalize results
   * @param {string} [userParameters.segments] - User segments
   * @param {string} [userParameters.testCells] - User test cells
   * @param {string} [userParameters.userIp] - Origin user IP, from client
   * @param {string} [userParameters.userAgent] - Origin user agent, from client`

2022-10-26 00:38 UTC, sblaurock commented
@stanlp1 do we think it'd be possible to migrate some of the changes we made in the commit range here into this PR? https://github.com/Constructor-io/constructorio-client-javascript/compare/3a99b4a...cb4ae4f

bit more detailed testing and some cleanup. if it's a big burden let me know and I can take a shot at it

2022-10-26 00:47 UTC, stanlp1 commented
> @stanlp1 do we think it'd be possible to migrate some of the changes we made in the commit range here into this PR? [Constructor-io/constructorio-client-javascript@3a99b4a...cb4ae4f](https://github.com/Constructor-io/constructorio-client-javascript/compare/3a99b4a...cb4ae4f)
> 
> bit more detailed testing and some cleanup. if it's a big burden let me know and I can take a shot at it

👍 Yep, can take care of that.

2022-11-06 16:04 UTC, sblaurock approved these changes
Made a few small updates - should be ready to go.

2022-11-08 19:33 UTC, jjl014 commented on src/modules/quizzes.js
> +    if (a) {
Let's change from `a` => `answers` all where everywhere

2022-11-09 19:01 UTC, sblaurock requested changes
`a` => `answers`

2022-11-11 19:10 UTC, jjl014 commented on src/modules/quizzes.js
> +  getNextQuestion(quizId, parameters, userParameters = {}, networkParameters = {}) {
The votes are in! `getNextQuestion` will be changed to `getQuizNextQuestion` 👍

2022-11-14 21:09 UTC, esezen commented on src/modules/quizzes.js
> +/* eslint-disable object-curly-newline, no-underscore-dangle */ const qs = require('qs');
qs got moved to the first line somehow 🤔

2022-11-14 21:12 UTC, esezen commented on src/modules/quizzes.js
> +  getNextQuizQuestion(quizId, parameters, userParameters = {}, networkParameters = {}) {
Based on Jimmy's comment, should this be `getQuizNextQuestion`?

2022-11-14 21:12 UTC, esezen commented on src/modules/quizzes.js
> +   * constructorio.quizzes.getNextQuizQuestion('quizId', {
Based on Jimmy's comment, should this be getQuizNextQuestion?

2022-11-14 21:12 UTC, esezen commented on src/modules/quizzes.js
> +   * @function getNextQuizQuestion
Based on Jimmy's comment, should this be getQuizNextQuestion?

2022-11-14 21:15 UTC, esezen commented
Left two small comments rest LGTM!

2022-11-15 15:10 UTC, esezen approved these changes
LGTM! Let's get a final review from @jjl014 and 🚢 this

2022-11-16 00:07 UTC, jjl014 approved these changes
This looks solid to me! Thank you for making all of the changes. You are the best! 😄

2022-11-16 20:47 UTC, merged